### ISSUE TITLE
Question about Paper

### ISSUE THREAD

**Issue by yangmingming629** [HKUDS/DiffKG#1]
Hi,
The DiffKG is an amazing and dramatic work. Thank you very much for sharing your code. I would greatly appreciate it if you could provide the corresponding paper that has been accepted by WSDM 2024？My email is yangmingming629@stu.xjtu.edu.cn. Thank you very much for your help. 
I look forward to your response.

Best Regards.

**Comment by yangqin-jiang** [comment]
Hi,

Thanks for your interest  in our work. We will release our paper on arxiv as soon as possible (maybe in a week).

Sincerely,
Yangqin

**Comment by yangmingming629** [comment]
> Hi,
> 
> Thanks for your interest in our work. We will release our paper on arxiv as soon as possible (maybe in a week).
> 
> Sincerely, Yangqin

Hi, 

Thank you for your reply! Looking forward to you releasing your paper. Thanks again.

Best Regards.

**Comment by yangqin-jiang** [comment]
Hi,

Thank you for your attention to our work. We have released our paper on arxiv (https://arxiv.org/pdf/2312.16890.pdf)

Sincerely,
Yangqin
