### ISSUE TITLE
Model input problem

### ISSUE THREAD

**Issue by godpromax** [HKUDS/DiffKG#2]
Hello, I would like to ask how the data set of the model input of the diffkg algorithm is processed. The paper does not explain it in detail. I am curious about how the kg.txt and pkl files are generated. I tried to use some knowledge graph triples for input, but found that the dimensions of the sparse matrix constructed by the pkl file do not match. If you can explain to me how the original data set is processed to obtain kg and two pkl files, I will be very grateful to you.

**Comment by yangqin-jiang** [comment]
Thank you for your interest in our work. 

The .pkl file is a sparse matrix file of user-item interactions, with a shape of [n_u, n_i], where n_u and n_i represent the number of users and items in the entire dataset (training set + testing set). As for the kg.txt file, it consists of triples [head, relation, tail], where head and tail are entities. The entities in KGs and items in the user-item interaction matrix share the same set of IDs. In our work, the number of entities in the three datasets is greater than the number of items (meaning some entities do not appear in the interaction matrix). Therefore, as long as the constructed knowledge graph contains all the items in the interaction matrix, there should be no problem. I'm not quite sure about the specific issue you mentioned regarding the dimension mismatch of the interaction matrix, but I hope my answer is helpful to you. 

If you still have any questions, please let me know.
