### ISSUE TITLE
关于mse损失的问题

### ISSUE THREAD

**Issue by akajinchen** [HKUDS/DiffKG#3]
https://github.com/HKUDS/DiffKG/blob/c4f607ad22c5f00dc88b7feb379f574e3c9cd331/Model.py#L262
这里的mse损失会不会给target传梯度呢 我们的目的是吧output逼近target，但是这里也给target传梯度是不是会有问题呢

**Comment by yangqin-jiang** [comment]
这里的x_start只是一个torch tensor对象，它是不可学习的，所以也是不会接受梯度的，在让model_output逼近x_start的过程中只有model_output会被优化，而x_start应该是保持不动的。

**Comment by yangqin-jiang** [comment]
我注意到您的疑问已经在DiffRec的issue得到解答，因此关闭此issue。

**Comment by akajinchen** [comment]
> 我注意到您的疑问已经在DiffRec的issue得到解答，因此关闭此issue。

是的，我当时没有仔细看您这里的训练过程只看了损失，其实和L-DiffRec的不太一致，所以提出了错误的问题，也感谢您的耐心回答和开源工作
