### ISSUE TITLE
关于代码

### ISSUE THREAD

**Issue by zqj65** [HKUDS/DiffKG#4]
你好，请问有单独的知识图谱+扩散模型给知识图谱去噪（只去噪）的代码吗

**Comment by yangqin-jiang** [comment]
你好，如果想要只是对KG通过扩散模型去噪，可以去除我们工作中的collaborative knowledge graph convolution (i.e., CKGC)模块，剩下的扩散模型部分就是仅仅依靠diffusion的过程来实现KG去噪。
