### ISSUE TITLE
实验配置

### ISSUE THREAD

**Issue by wzbjcjz** [HKUDS/DiffKG#5]
你好我可以询问一下本篇代码在运行时所需要的硬件实验配置吗？万分感谢

**Comment by yangqin-jiang** [comment]
你好，本工作的实验都是在3090GPU（24G）上完成的，CPU和内存没有特别的要求。一般的消费级别GPU即可支持实验。

**Comment by wzbjcjz** [comment]
作者您好，很抱歉再次打扰您，后续我也对该实验进行了复现可是发现该代码对内存要求非常高，同时我也更换了相应硬件设备提高内存还是没有满足这个要求想问下您是怎么解决这个问题的呢？

**Comment by yangqin-jiang** [comment]
可以讲一下您的硬件条件（主要是GPU显存），以及运行该代码所使用的数据集吗（如果不是DiffKG工作中所使用的三个数据集，可以给出数据集的一些信息吗，比如知识图谱实体的数量，UI图user,item,edge的数量）

**Comment by wzbjcjz** [comment]
感谢您的回复，因为是在校使用服务器操作的，我先后使用了A100（40GB)在Windows上、L20(48GB)在Linux上进行运行都出现了问题；还是在原数据集上进行运行的，没有更换数据集；另外所针对使用GPU块数有要求吗？麻烦您了

**Comment by yangqin-jiang** [comment]
在原数据集上运行是使用项目中提供的超参数命令吗，项目里对三个数据集提供的三条运行命令里面的超参数配置，应该都可以在单卡3090 24G的配置下运行（这也是我跑DiffKG所有实验的硬件资源），A100（40G）和L20（48G）应该是完全没问题的。可能运行的速度确实会比较慢，尤其是LastFM数据集，因为它比较稠密且KG的关系也很多。

**Comment by wzbjcjz** [comment]
是的，是使用的项目中所提供的超参数命令，没有更改其他的，按道理是应该可以跑通的但是现在是直接出现报错，还没有运行起来（5555），下图是在A100服务器上运行出现的问题，就是不太清楚哪里出问题了；万分感谢您的解答，实在是打扰了
![1](https://github.com/HKUDS/DiffKG/assets/145132134/a7043d6f-8cd4-4ba9-8a07-07f66ece8dc0)

**Comment by yangqin-jiang** [comment]
看上去是出现在self.kg_matrix从稀疏转化为稠密的过程中出现了问题，这块会需要较大的内存进行操作，看错误好像是内存不足，如你所说是在服务器上运行，按理说服务器的内存资源应该是很充足的，你可以检查一下实验所用服务器的内存资源情况，并优先尝试KG实体数较少的数据集（e.g., MIND）

**Comment by wzbjcjz** [comment]
嗯嗯好的，感謝您的回答，我再去查一查这里的问题

**Comment by congyaya** [comment]
我也遇到了同样的问题，请问你解决了吗
