### ISSUE TITLE
high percentage of physical memory

### ISSUE THREAD

**Issue by swx9142592** [HKUDS/DiffKG#7]
I was able to run your code successfully, but I noticed through the task manager that when running the last-fm dataset, the CPU utilization is extremely high, and the usage percentage of physical memory is extremely high, causing the computer to crash very easily, have you encountered this problem, and how did you solve it? I look forward to receiving your answer. My computer configuration is i7-12700KF, 32gb with RAM, 4090 graphics card.
![微信图片_20241023191641](https://github.com/user-attachments/assets/25a47e13-394b-46a6-83ec-9e994ad76686)
![1729730931183](https://github.com/user-attachments/assets/6cf18628-3a0b-49c8-9bcf-a9371d46e71d)

![1729731080346](https://github.com/user-attachments/assets/f7f87e86-83cd-4372-b425-8202af81f376)

**Comment by yangqin-jiang** [comment]
Hi,

Thanks for bringing this serious issue to our attention ! I have fixed it in the latest code. I believe you can run the code on your computer now. 

Sincerely,
Yangqin Jiang
